config/routes.rb
InteriorApp::Application.routes.draw do

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :projects
  resources :tasks
  resources :contact

  root to: 'static_pages#home'

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/edit_profile', to: 'users#edit'

  match '/projects', to: 'projects#index'
  match '/contacts', to: 'projects#index'
 
  match '/weekly', to:'projects#show_weekly', as: :weekly
  match '/edit_weekly/:id', to:'projects#edit_weekly', as: :edit_weekly

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :address1, :address2, :contact, :dist, :email, :fax, :mfr, :specialty, :tel, :webpage
end

app/models/project.rb
class Project < ActiveRecord::Base
	attr_accessible :project_name, :tasks_attributes
	before_save {|project| project.project_name = project_name.downcase}

	has_many :tasks, dependent: :destroy
	accepts_nested_attributes_for :tasks, reject_if: :all_blank, allow_destroy: :true

	validates :project_name, length: {minimum: 3}
	validates :project_name, presence: true
	validates :project_name, uniqueness: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :project_id, :status
  belongs_to :project

  validates :project_id, presence: true
  validates :description, presence: true, uniqueness: true


  default_scope order: 'tasks.created_at ASC'
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  # attr_accessible :title, :body

attr_accessible :username, :email, :password, :password_confirmation

	before_save {|user| user.username = username.downcase }
	before_save {|user| user.email = email.downcase }

	validates :password, confirmation: true
	validates :password, length: {minimum: 7}
	validates :password, presence: true
	validates :password_confirmation, presence: true

	validates :username, presence: true, uniqueness: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX }, uniqueness: {case_sensitive: false}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :require_login

  protected

  def not_authenticated
  	redirect_to root_path, :alert => "Please login first."
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	def index
		@contacts = Contact.all
		if @contacts.empty?
			flash[:error] = "Threre are no contacts to view, create new contact to proceed"
		end
		
	end

	# def create
		
	# end

	def new
		@contact = Contact.new
	end

	# def edit
		
	# end

	# def show
		
	# end

	# def update
		
	# end

	# def destroy
		
	# end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	skip_before_filter :require_login, :except => [:destroy]

	# def index
	# 	@projects = Project.all
	# 	if @projects.empty?
	# 		flash[:error] = "Threre are no projects to view, create new project to proceed"
	# 	end
	# 	@project = Project.new
	# end

	def create
		@project = Project.new(params[:project])
		if @project.save
			flash[:success] = "Project was successfully created"
			redirect_to weekly_path
		else
			render :new
		end
	end

	def update
		@project = Project.find(params[:id])
		@project.update_attributes(params[:project])
		flash[:success] = "Project has been successfully updated."
		# respond_with (@project)
		redirect_to '/weekly'
	end


	def destroy
		Project.find(params[:id]).destroy
		flash[:success] = "Project has been deleted."
		redirect_to '/weekly'
	end



	def show_weekly
		@projects = Project.all
		@tasks = Task.all
		@active = Task.find(:all, :conditions => {:status => true})
		@inactive = Task.find(:all, :conditions => {:status => false})

		if @projects.empty?
			flash[:error] = "Threre are no projects to view, create new project to proceed"
		end
		@project = Project.new
	end


	def edit_weekly
		@project = Project.find(params[:id])
		
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_filter :require_login, :except => [:destroy]

  def new
  	@user = User.new
  end


  def create
  	if @user = login(params[:username],params[:password],params[:remember_me])
  		flash[:success] = "Welcome to the Sample App!"
      redirect_back_or_to root_path

  	else
  		flash[:error] = "Email or password was invalid"
  		redirect_to :root
  	end
  	
  end



  def destroy
  	logout
  	redirect_to root_path, notice: "Logged out!"
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	skip_before_filter :require_login, :only => [:home, :help]
	
	def home
	end

	def help
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login, :only => [:index, :new, :create]

  def new
  	@user = User.new
  end



  def create
  	@user = User.new(params[:user])
  	if @user.save
      flash[:success] = "User was successfully created"
  		redirect_to root_path
  	else
  		render :new
  	end
  end



  def edit
    @user = User.find(session[:user_id])
  end



  def update
    @user = User.find(session[:user_id])
      if @user.update_attributes(params[:user])
        flash[:success] = "User was successfully updated"
        redirect_to root_path
      else
        render :action => "edit"
      end
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contact/_contact_modal.html.erb
<!-- Modal -->
<div id="addContactModal" class="modal hide fade" tabindex="-1" data-replace="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create new project</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@contact) do |f| %>
    <%= render 'shared/contact_error_messages' %>

    <%= f.label :mfr, "Manufacturer" %>
    <%= f.text_field :mfr, placeholder:"Manufacturer name" %>
    
    <%= f.label :dist, "Distributor" %>
    <%= f.text_field :dist, placeholder:"Distributor name" %>
    
    <%= f.label :contact, "Contact" %>
    <%= f.text_field :contact, placeholder:"Contact name" %>
    
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, placeholder:"Contact E-mail" %>
    
    <%= f.label :address1, "Address Line 1" %>
    <%= f.text_field :address1, placeholder:"Street Address" %>
    
    <%= f.label :address2, "Address Line 2" %>
    <%= f.text_field :address2, placeholder:"State, Zipcode" %>
    
    <%= f.label :tel, "Telephone Number" %>
    <%= f.text_field :address2, placeholder:"xxx-xxx-xxx" %>

    <%= f.label :fax, "Fax Number" %>
    <%= f.text_field :fax, placeholder:"xxx-xxx-xxx" %>

    <%= f.label :webpage, "Webpage Address" %>
    <%= f.text_field :webpage, placeholder:"http://" %>

    <%= f.label :specialty, "Specialty" %>
    <%= f.text_field :specialty, placeholder:"Furniture, Flooring, etc..." %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Create Contact", class: "btn btn-custom" %>
    <% end %>
  </div>
</div>

app/views/contact/index.html.erb
<!-- Sub-title for the nav -->
<% provide(:title, '// Contact') %>


<!-- content -->
<div class="span10 offset1">

	<div class="title">
		<h1>// Contact</h1>
	</div>

	<!-- Button to trigger modal -->
	<div class="shopgray module-menu">
		<i class="icon-plus black"></i>
		<%= link_to "Add Contact", new_contact_path %>
		<i class="icon-print black" style="margin-right: 5px; margin-left: 20px;"></i>
		<%= link_to 'PDF', '#' %>
	</div>
</div>

app/views/contact/new.html.erb
<!-- Sub-title for the nav -->
<% provide(:title, '// Register') %>



<div class="row">
  <div class="span6 offset3">
    <div class="title-static">
    <h1>// Add Contact</h1>
    </div>
    <%= form_for(@contact) do |f| %>
    <%= render 'shared/contact_error_messages' %>

    <%= f.label :mfr, "Manufacturer" %>
    <%= f.text_field :mfr, placeholder:"Manufacturer name" %>
    
    <%= f.label :dist, "Distributor" %>
    <%= f.text_field :dist, placeholder:"Distributor name" %>
    
    <%= f.label :contact, "Contact" %>
    <%= f.text_field :contact, placeholder:"Contact name" %>
    
    <%= f.label :email, "Email" %>
    <%= f.text_field :email, placeholder:"Contact E-mail" %>
    
    <%= f.label :address1, "Address Line 1" %>
    <%= f.text_field :address1, placeholder:"Street Address" %>
    
    <%= f.label :address2, "Address Line 2" %>
    <%= f.text_field :address2, placeholder:"State, Zipcode" %>
    
    <%= f.label :tel, "Telephone Number" %>
    <%= f.text_field :address2, placeholder:"xxx-xxx-xxx" %>

    <%= f.label :fax, "Fax Number" %>
    <%= f.text_field :fax, placeholder:"xxx-xxx-xxx" %>

    <%= f.label :webpage, "Webpage Address" %>
    <%= f.text_field :webpage, placeholder:"http://" %>

    <%= f.label :specialty, "Specialty" %>
    <%= f.text_field :specialty, placeholder:"Furniture, Flooring, etc..." %>

    <%= f.submit "Create Contact", class: "btn btn-large btn-custom btn-offset pull-right" %>

    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
  <small>
    Designed by <span class="wontae"> Wontae Yang </span>
  </small>
  <nav>
    <ul>
      <li><a href="http://news.railstutorial.org/">SHoP</a></li>
      <li><%= link_to "Contact", '#' %></li>
      
    </ul>
  </nav>

app/views/layouts/_header.html.erb
<header class="navbar navbar-static-top navbar-inverse">
  <div class="navbar-inner">
<div class="container-fluid">
      <div class="span10 offset1">

   <a class="brand" href="<%= root_url %>">
    <strong>
      SHoP
    </strong>
    <span class="idg">
      <%= yield :title %>
    </span>
  </a>
  

  <!--  <div class="nav-collapse collapse"> -->
  <ul class="nav pull-right">
    <% if current_user %>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
       <span><i class="icon-user visible-phone"></i>
         <span class="hidden-phone"> Welcome, </span></span>
         <%= current_user.email.upcase.split("@").first %>
         <b class="caret white-caret"></b>
       </a>
       <ul class="dropdown-menu shopgray">
        <li>
          <span>
            <i class="icon-pencil dropdown-menu-icon black"></i>
            <%= link_to "Edit Profile", edit_profile_path %>
          </span>
        </li>
        <li>
          <span>
            <i class="icon-cogs  dropdown-menu-icon black"></i>
            <%= link_to "Settings", '#' %>
          </span>
        </li>
        <li class="divider"></li>
        <li>
          <span>
            <i class="icon-signout dropdown-menu-icon black"></i>
            <%= link_to "Sign out", signout_path, method: "delete"%>
          </span>
        </li>
      </ul>
    </li>
    <% else %>
    <li>
      <%= link_to "Register", signup_path %>
    </li>
    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        Sign In
        <b class="caret white-caret"></b>
      </a>
      <ul class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
        <%= form_tag sessions_path do %>
        <%= label_tag :username %>
        <%= text_field_tag :username %>

        <%= label_tag :password %>
        <%= password_field_tag :password %>

        <%= check_box_tag :remember_me, 1, params[:remember_me], :style => "float: left;" %>
        <%= label_tag :remember_me %>
        

        <%= submit_tag "Sign in", class: "btn btn-custom" %>
        <% end %>
      </ul>
    </li>
    <% end %>
  </ul>

</div>
  </div>

  
</div>
</header>

app/views/layouts/_menu.html.erb
 <div class="navbar-static-top">
 	<div class="navbar-inner menu-bar">
 		<div class="container-fluid">
 			<div class="span10 offset1">

 				<ul>
 					<li><%= link_to "Home", root_path%></li>
 					<li><%= link_to "Weekly", weekly_path %></li>
 					<li><a href="#">Material DB</a></li>
 					<li><%= link_to "Contact", contact_index_path %></li>
 				</ul>
 			</div>
 		</div>
 		
 	</div>
 </div>
</header>

app/views/layouts/_modal.html.erb
<!-- Modal -->
<div id="addProjectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create new project</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@project) do |f| %>
    <%= render 'shared/project_error_messages' %>
    <%= f.label :project_name %>
    <%= f.text_field :project_name, placeholder:"Project name" %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Create project", class: "btn btn-custom" %>
    <% end %>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= favicon_link_tag image_path("favicon.ico") %>

	<title>SHoP</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
	<%= render 'layouts/shim' %>

</head>

<body>
	<%= render 'layouts/header' %>
	<% if current_user %>
	<%= render 'layouts/menu' %>
	<% end %>

	<div class="wrapper">
		<div class="container-fluid">

			<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>" >
				<button type="button" class="close" data-dismiss="alert">&times;</button>
				<%= value %>
			</div>
			<% end %>

			<%= yield %>

		</div>

	</div>
	<div class="push"></div>
	<div class="footer">
		<div class="container">
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</div>
</body>
</html>

app/views/projects/_project_modal.html.erb
<!-- Modal -->
<div id="addProjectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Create new project</h3>
  </div>
  <div class="modal-body">
    <%= form_for(@project) do |f| %>
    <%= render 'shared/project_error_messages' %>
    <%= f.label :project_name %>
    <%= f.text_field :project_name, placeholder:"Project name" %>
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <%= f.submit "Create project", class: "btn btn-custom" %>
    <% end %>
  </div>
</div>

app/views/projects/_task_fields.html.erb
<div class="nested-fields">
	<div class="field">
		
		
		<div class="input-prepend input-append">
			<span class="add-on"><%= f.check_box :status  %></span>

			<span class="input-container">
				<%= f.text_field :description, class: "span5" %>
			</span>
			<span class="add-on">
				<i class="icon-trash black"></i>
				<%= link_to_remove_association "Remove", f %>
			</span>
		</div>
		
		
	</div>
	
	
</div>

app/views/projects/backup_task_fields.html.erb
<div class="nested-fields">
	<div class="field">
		
		<%= f.label :description, "Task Description" %>
		<%= f.text_field :description, class: "span7" %>
		<%= f.check_box :status, class: "status pull-right" %>
		<%= f.label :status, class: "status inline pull-right" %>
		
	</div>
	<span class="shopgray">
		<i class="icon-trash black"></i>
		<%= link_to_remove_association "remove task", f %>
	</span>
	
</div>

app/views/projects/edit_weekly.html.erb
<div class="row">
  <div class="span8 offset2">
    <div class="title-static">
      <h1>// Edit Project</h1>
    </div>
    <%= form_for(@project) do |f| %>
    <%= render 'shared/project_error_messages' %>

    <%= f.label :project_name, "Project Name" %>
    <%= f.text_field :project_name %>
    <div id="tasks">
      <div id="task-container">
        <%= f.fields_for :tasks do |task| %>
        <%= render 'task_fields', :f => task %>
        <% end %>
      </div>




      <div class="task-buttons">
        <div class="shopgray">
          <i class="icon-plus black"></i>
          <%= link_to_add_association 'Add Task', f, :tasks %>
          <%= f.submit "Save changes", class: "btn btn-custom pull-right" %>
        </div>
        
      </div>

      <% end %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<!-- Sub-title for the nav -->
<% content_for :title do %>
<span class="hidden-phone">// Interiors Project Directory</span>
<span class="visible-phone">// Projects</span>
<% end %>


<!-- title -->

<div class="center title">
	<h1>// Projects</h1>
</div>

<div class="project-list">

	<% @projects.each do |p| %>

	<div class="projects">
	<h2>/ <%= p.project_name.upcase %> </h2>
	<div class="project-links">
		<i class="icon-calendar"></i>
		<%= link_to 'Weekly', weekly_path(p) %>
		<i class="icon-tags"></i>
		<%= link_to 'Material', "#" %>
		<i class="icon-remove"></i>
		<%= link_to "Delete", project_path(p), method: "delete"%>
	</div>
</div>

<% end %>

</div>



<!-- modal -->

<%= render 'layouts/modal' %>

app/views/projects/new.html.erb
<h1 class="center top-offset">Create new project</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@project) do |f| %>
    <%= render 'shared/project_error_messages' %>
    <%= f.label :project_name %>
    <%= f.text_field :project_name, placeholder:"Project name" %>

    <%= f.submit "Create project", class: "btn btn-large btn-custom" %>

    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<!-- Custom menu for the page -->
<% content_for :menu do %>
	<li class="nav-header">ACTION</li>
	<li><a href="#myModal" data-toggle="modal">Add task</a></li>
	
<% end %>

<!-- title -->

<div class="center title">
	<h1>// Interior Weekly</h1>
</div>

<div class="weekly">
	<h2><%= @project.project_name.upcase %></h2>
	<% @tasks.each do |p| %>
		<div class="inline">
		<a href="#" data-toggle="modal"><i class="icon-plus"></i></a>
		<a href="#" data-toggle="modal"><i class="icon-minus"></i></a>	
		<h2> <%= link_to p.project_name.upcase, p %> </h2>
		<div></div>
		</div>

    <div>
      <% if p.tasks.any? %>
        <ol class="tasks">
          <%= render @tasks %>
        </ol>
      <% end %>


	<% end %>

</div>




<!-- modal -->

<%= render 'layouts/modal' %>

app/views/projects/show_weekly.html.erb
<!-- Sub-title for the nav -->
<% content_for :title do %>
<span class="hidden-phone">// Interiors Weekly</span>
<span class="visible-phone">// Weekly</span>
<% end %>

<!-- content -->

<div class="span10 offset1">


	<div class="title">
		<h1 class="hidden-phone">// Interiors Weekly</h1>
		<h1 class="visible-phone">// Weekly</h1>
	</div>


	<!-- Button to trigger modal -->
	<div class="shopgray module-menu">
		<i class="icon-plus black"></i>
		<a href="#addProjectModal" data-toggle="modal">Add Project</a>
		<i class="icon-print black" style="margin-right: 5px; margin-left: 20px;"></i>
		<%= link_to 'PDF', '#' %>
	</div>

	<!-- Project listing starts here -->


	<% @projects.each do |p| %>

	<div class="project-list">

		<div class="project-title">
			<h2>/ <%= p.project_name.upcase %> 
				<span class="project-links pull-right" >
					<i class="icon-pencil"></i>
					<%= link_to 'Edit', edit_weekly_path(p.id) %>
					<i class="icon-remove"></i>
					<%= link_to "Delete", project_path(p), method: "delete", confirm: "Are you sure?" %>

				</span>
			</h2>

		</div>

		<% if p.tasks.any? %>
		<div class="task-container">
			<h5>Active Tasks (<%= p.tasks.where(:status => true).count %>)</h5>
			<table class="task-table">
				<tbody>
					<% p.tasks.each do |t| %>
					<% if t.status == true %>
					<tr>
						<td class="task-status">
							<i class="icon-circle shopgreen left"></i> 
						</td>
						<td>
							<%= t.description %>
						</td>
					</tr>
					<% end %>
					<% end %>
				</tbody>
			</table>
			<h5>Inactive Tasks (<%= p.tasks.where(:status => false).count %>)</h5>
			<table class="task-table">
				<tbody>
					<% p.tasks.each do |t| %>
					<% if t.status == false %>
					<tr>
						<td class="task-status">
							<i class="icon-circle-blank left"></i>
						</td>
						<td>
							<%= t.description %>
						</td>
					</tr>
					<% end %>
					<% end %>
				</tbody>
			</table>
		</div>
		<% end %>
	</div>
	<% end %>

	<div class="statistics pull-right shopgray">
		<h5>Project Total: <%= @projects.count %></h5>
		<h5>Tasks Total: <%= @tasks.count %></h5>
		<h5>Active Tasks: <%= @active.count %></h5>
		<h5>Inactive Tasks: <%= @inactive.count %></h5>
	</div>
</div>





<!-- modal -->

<%= render 'project_modal' %>

app/views/shared/_contact_error_messages.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@project.errors.count, "error") %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_project_error_messages.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@project.errors.count, "error") %>.
    </div>
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<!-- Sub-title for the nav -->
<% content_for :title do %>
<span class="hidden-phone">// Interior Design Group</span>
<span class="visible-phone">// IDG</span>
<% end %>


<!-- Content -->
<div class="center">
	<div class="circular top-offset"> </div>
	<h1 class="shopgreen">Interior Design Group</h1>
	<h2>// Interior Weekly</h2>
	<h2>// Material Database</h2>
	<h2>// Contact</h2>

	<p>
		Please sign in above in the menu bar.
	</p>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<!-- Sub-title for the nav -->
<% provide(:title, '// Edit Profile') %>

<div class="row">
  <div class="span6 offset3">
    <div class="title-static">
    <h1>// Edit Profile</h1>
    </div>
   	<%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :username %>
      <%= f.text_field :username %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder:"Password" %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, placeholder:"Confirm password" %>

      <%= f.submit "Save changes", class: "btn btn-large btn-custom btn-offset pull-right" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<!-- Sub-title for the nav -->
<% provide(:title, '// Register') %>



<div class="row">
  <div class="span6 offset3">
    <div class="title-static">
    <h1>// Register</h1>
    </div>
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :username %>
    <%= f.text_field :username, placeholder:"Your ShoP initial" %>

    <%= f.label :email %>
    <%= f.text_field :email, placeholder:"Work e-mail" %>

    <%= f.label :password %>
    <%= f.password_field :password, placeholder:"Password" %>

    <%= f.label :password_confirmation, "Confirmation" %>
    <%= f.password_field :password_confirmation, placeholder:"Confirm password" %>

    <%= f.submit "Create my account", class: "btn btn-large btn-custom" %>

    <% end %>
  </div>
</div>